// Generate migrations/0002_seed.sql from app/data/network/*.ts
// Run: node scripts/seed-network.mjs
import { build } from 'esbuild'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

async function load(entry) {
  const r = await build({ entryPoints: [join(root, entry)], bundle: true, write: false, format: 'esm' })
  return import('data:text/javascript;base64,' + Buffer.from(r.outputFiles[0].text).toString('base64'))
}

const net = await load('app/data/network/index.ts')
const { contacts } = await load('app/data/network/contacts.ts')

const q = (s) => `'${String(s).replace(/'/g, "''")}'`
const j = (o) => q(JSON.stringify(o))

const lines = [
  '-- Migration number: 0002    generated by scripts/seed-network.mjs — do not hand-edit',
]
const nodeIds = new Set()
const edgeKeys = new Set()

function node(id, type, name, data) {
  if (nodeIds.has(id)) return
  nodeIds.add(id)
  lines.push(`INSERT INTO nodes (id, type, name, data) VALUES (${q(id)}, ${q(type)}, ${q(name)}, ${j(data)});`)
}
function edge(from, to, relation, data = {}) {
  const key = `${from}|${to}|${relation}`
  if (edgeKeys.has(key) || !nodeIds.has(from) || !nodeIds.has(to)) return
  edgeKeys.add(key)
  lines.push(`INSERT INTO edges (from_id, to_id, relation, data) VALUES (${q(from)}, ${q(to)}, ${q(relation)}, ${j(data)});`)
}

// Nodes first — order matters for FK references.
for (const o of net.organizations) node(o.id, 'org', o.name, { orgType: o.type, description: o.description, website: o.website })
for (const p of net.people) node(p.id, 'person', p.name, { aka: p.aka, boardStatus: p.boardStatus, boardRole: p.boardRole, roles: p.roles, notes: p.notes, links: p.links })
for (const v of net.networkVenues) node(v.id, 'venue', v.name, { address: v.address, area: v.area, venueType: v.type, description: v.description, website: v.website, hmabUse: v.hmabUse })
for (const e of net.networkEvents) node(e.id, 'event', e.name, { date: e.date, category: e.category, description: e.description, location: e.location, links: e.links })
for (const pr of net.programs) node(pr.id, 'program', pr.name, { programType: pr.type, description: pr.description, links: pr.links })

// Minimal person nodes for contact records with no people.ts entry.
const special = { 'hmab-board-account': 'hmab', 'tmo-staff': 'tmo' }
for (const c of contacts) {
  if (nodeIds.has(c.personId) || special[c.personId]) continue
  const name = c.personId.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ')
  node(c.personId, 'person', name, { notes: c.notes, minimal: true })
}

// Edges.
for (const p of net.people) for (const oid of p.organizations) edge(p.id, oid, 'member-of')
for (const o of net.organizations) for (const pid of o.people || []) edge(pid, o.id, 'member-of')
for (const e of net.networkEvents) {
  if (e.venueId) edge(e.id, e.venueId, 'hosted-at')
  for (const pid of e.people || []) edge(pid, e.id, 'involved-in')
  for (const oid of e.orgs || []) edge(oid, e.id, 'involved-in')
}
for (const pr of net.programs) if (pr.org && nodeIds.has(pr.org)) edge(pr.id, pr.org, 'run-by')

writeFileSync(join(root, 'migrations/0002_seed.sql'), lines.join('\n') + '\n')

// Contacts — private table. NEVER in migrations/ (that dir is committed to the
// public repo). Gitignored file, applied manually:
//   wrangler d1 execute houston-music-db [--local|--remote] --file=seed-private/contacts.sql
const priv = ['-- PRIVATE seed — gitignored, apply with wrangler d1 execute --file. Never commit.']
for (const c of contacts) {
  const target = special[c.personId] || c.personId
  if (!nodeIds.has(target)) continue
  priv.push(`INSERT OR REPLACE INTO contacts (node_id, emails, phones, notes) VALUES (${q(target)}, ${j(c.emails || [])}, ${j(c.phones || [])}, ${c.notes ? q(c.notes) : 'NULL'});`)
}
writeFileSync(join(root, 'seed-private/contacts.sql'), priv.join('\n') + '\n')
console.log(`nodes: ${nodeIds.size}, edges: ${edgeKeys.size}, contacts (private file): ${contacts.length}`)
